### ISSUE TITLE
Get server running using runServer callback

### ISSUE THREAD

**Issue by trystant** [cheesegits/family-farm#1]
Right now, running the server using the `node server.js` results in an error:

**Comment by cheesegits** [comment]
Error:
Resource interpreted as Document but transferred with MIME type application/json: "http://localhost:8080/receipts".

This same GET error happens 1) using mockData in the server.js file on a direct 'localhost:8080/receipts' connection, and 2) using a mongoose Schema + mongoose.connect configuration.   DevTools: Network only shows a single document being loaded.
